### ISSUE TITLE
Set access rights for shared drive on summon

### ISSUE THREAD

**Issue by telto** [denise97/dhl2021#23]
Set access rights for shared drive on summon for each folder.

**Comment by telto** [comment]
Command to be executed: `chgrp -R delab-arnrich-mpss2021ba1 scripts`
* `chgrp` change group ownership
* `-R` change permissions recursively in all subdirectories below the specified directory
* `delab-arnrich-mpss2021ba1` group name
* `scripts` exemplary directory name

I do not have the permission to adjust the access permissions for folders/files created by Nina and Denise.
You guys have to apply the command as well.

**Comment by ninaihde** [comment]
Thanks for investigating but I still can't move files to `/data` or `/plots`. I think there is something like `chmod -R g+rwx scripts` missing,  which I just tried with the `/scripts` folder . Could you try moving a file to the `/scripts` folder?

**Comment by telto** [comment]
Moving file to `/scripts` works for me.

Please test whether you can do the same with `/data` and `/plots` now.

**Comment by ninaihde** [comment]
Yes, it works too.
