### ISSUE TITLE
Read up on Arima + Alternatives

### ISSUE THREAD

**Issue by telto** [denise97/dhl2021#32]
Read up on Arima in context of other models that are potential alternatives for our use case (irregular sampling rates).

**Comment by telto** [comment]
Maybe interesting https://medium.com/unit8-machine-learning-publication/training-forecasting-models-on-multiple-time-series-with-darts-dc4be70b1844

**Comment by ninaihde** [comment]
I summarized my findings in the document "Handling of Irregular Data & Forecasting Alternatives to ARIMA", which you can find in our shared OneDrive in the `/Readings` folder.
