### ISSUE TITLE
Create register of scripts

### ISSUE THREAD

**Issue by telto** [denise97/dhl2021#42]
Create tabulary overview for scripts as Word document on OneDrive consisting of the following columns:
* Script name
* Script location
* Input file
* Output file
* Comment

Link this Word  file in the GitHub README

**Comment by denise97** [comment]
Can be found in One Drive: https://onedrive.live.com/edit.aspx?cid=ea16765e72b7f0c0&page=view&resid=EA16765E72B7F0C0!518173&parId=EA16765E72B7F0C0!518171&app=Excel

**Comment by denise97** [comment]
Furthermore, I started a pptx to visually show the connection between relevant scripts. Can be also found in the Document Folder in OneDrive.
