### ISSUE TITLE
Implement 1D-CNN as first alternative to Arima

### ISSUE THREAD

**Issue by telto** [denise97/dhl2021#43]
**Input from Weekly on 2021-06-01:**
We learned that a previous Master project group investigated methods for dealing with irregular sampling rates. Short conclusion: Next steps for us (after Arima) is to check out Recurrent Neural Networks.

**Update from Weekly on 2021-06-08:**
We will use a 1D-CNN instead of a RNN as we hope to get more accurate results with a CNN.

**ToDo:**
Implement 1D-CNN based on resampled chunks (common sampling rate) in Python.

**Comment by ninaihde** [comment]
We decided to implement a second approach with RNNs instead of 1D-CNNs.
